#Application Configuration
server:
  port: 8086
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  #h2:
    #console:
      #enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    driverClassName: oracle.jdbc.OracleDriver
    username: rrbolivarna
    password: Soporte1

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"